export { default as alfajoresChocolate } from './alfajoresChocolate.jpeg';
export { default as alfajoresCoco } from './alfajoresCoco.jpeg';
export { default as bizcochos } from './bizcochos.jpeg';
export { default as budinChocolate } from './budinChocolate.jpeg';
export { default as logo } from './logo.jpeg';
export { default as medialunasChocolate } from './medialunasChocolate.jpeg';
export { default as medialunasCoco } from './medialunasCoco.jpeg';
export { default as panCenteno } from './panCenteno.jpeg';
export { default as panIntegralSemillas } from './panIntegralSemillas.jpeg';
